use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use sha2::{Digest, Sha256};

use crate::error::{Error, Result};

#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) struct RecordEntry {
    pub path: String,
    pub hash: Option<String>,
    pub size: Option<u64>,
}

impl RecordEntry {
    /// Builds a RECORD entry for generated bytes, computing the wheel-standard
    /// URL-safe, unpadded sha256 digest and size.
    pub(crate) fn from_bytes(path: impl Into<String>, bytes: &[u8]) -> Self {
        let digest = URL_SAFE_NO_PAD.encode(Sha256::digest(bytes));
        Self {
            path: path.into(),
            hash: Some(format!("sha256={digest}")),
            size: Some(bytes.len() as u64),
        }
    }
}

pub(crate) fn parse_record(text: &str, label: &str) -> Result<Vec<RecordEntry>> {
    let mut entries = Vec::new();
    for (line_index, line) in text.lines().enumerate() {
        if line.is_empty() {
            continue;
        }
        let fields = parse_csv_line(line).map_err(|message| {
            Error::UnsupportedArtifact(format!(
                "invalid RECORD line {} in {label}: {message}",
                line_index + 1
            ))
        })?;
        if fields.len() != 3 {
            return Err(Error::UnsupportedArtifact(format!(
                "invalid RECORD line {} in {label}: expected 3 fields, found {}",
                line_index + 1,
                fields.len()
            )));
        }
        if fields[0].is_empty() {
            return Err(Error::UnsupportedArtifact(format!(
                "invalid RECORD line {} in {label}: empty path",
                line_index + 1
            )));
        }
        let size = if fields[2].is_empty() {
            None
        } else {
            Some(fields[2].parse::<u64>().map_err(|_| {
                Error::UnsupportedArtifact(format!(
                    "invalid RECORD line {} in {label}: invalid size `{}`",
                    line_index + 1,
                    fields[2]
                ))
            })?)
        };
        entries.push(RecordEntry {
            path: fields[0].clone(),
            hash: (!fields[1].is_empty()).then(|| fields[1].clone()),
            size,
        });
    }
    Ok(entries)
}

/// Serializes wheel RECORD rows using URL-safe, unpadded sha256 hashes.
///
/// Entries with `hash` and `size` set are emitted with those values. The
/// `.dist-info/RECORD` entry is always emitted with empty hash and size fields,
/// as required by the wheel spec. Paths are CSV-escaped so generated and
/// relocated paths can be recorded verbatim.
pub(crate) fn write_record(entries: &[RecordEntry]) -> String {
    let mut text = String::new();
    for entry in entries {
        push_csv_field(&mut text, &entry.path);
        text.push(',');
        if !is_record_self_entry(&entry.path) {
            if let Some(hash) = &entry.hash {
                push_csv_field(&mut text, hash);
            }
        }
        text.push(',');
        if !is_record_self_entry(&entry.path) {
            if let Some(size) = entry.size {
                text.push_str(&size.to_string());
            }
        }
        text.push('\n');
    }
    text
}

fn is_record_self_entry(path: &str) -> bool {
    path.ends_with(".dist-info/RECORD")
}

fn push_csv_field(out: &mut String, field: &str) {
    if !field.bytes().any(|byte| matches!(byte, b',' | b'"' | b'\n' | b'\r')) {
        out.push_str(field);
        return;
    }

    out.push('"');
    for ch in field.chars() {
        if ch == '"' {
            out.push('"');
        }
        out.push(ch);
    }
    out.push('"');
}

fn parse_csv_line(line: &str) -> std::result::Result<Vec<String>, String> {
    let mut fields = Vec::new();
    let mut field = String::new();
    let mut chars = line.chars().peekable();
    let mut quoted = false;

    while let Some(ch) = chars.next() {
        match ch {
            '"' if quoted && chars.peek() == Some(&'"') => {
                field.push('"');
                chars.next();
            }
            '"' => quoted = !quoted,
            ',' if !quoted => {
                fields.push(std::mem::take(&mut field));
            }
            _ => field.push(ch),
        }
    }

    if quoted {
        return Err("unterminated quoted field".to_owned());
    }
    fields.push(field);
    Ok(fields)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_record_rows_with_empty_hash_for_record_itself() {
        let entries = parse_record(
            "pkg/__init__.py,sha256=abc,12\npkg-1.0.dist-info/RECORD,,\n",
            "fixture",
        )
        .expect("record");

        assert_eq!(entries[0].path, "pkg/__init__.py");
        assert_eq!(entries[0].hash.as_deref(), Some("sha256=abc"));
        assert_eq!(entries[0].size, Some(12));
        assert_eq!(entries[1].path, "pkg-1.0.dist-info/RECORD");
        assert_eq!(entries[1].hash, None);
        assert_eq!(entries[1].size, None);
    }

    #[test]
    fn parses_quoted_commas() {
        let entries = parse_record("\"pkg/data,1.txt\",sha256=abc,4\n", "fixture").expect("record");
        assert_eq!(entries[0].path, "pkg/data,1.txt");
    }

    #[test]
    fn writes_url_safe_no_pad_sha256_rows() {
        let entry = RecordEntry::from_bytes("../../bin/demo", b"hello");
        let record = write_record(&[entry]);

        assert_eq!(
            record,
            "../../bin/demo,sha256=LPJNul-wow4m6DsqxbninhsWHlwfp0JecwQzYpOLmCQ,5\n"
        );
    }

    #[test]
    fn writes_empty_record_self_row() {
        let record = write_record(&[RecordEntry {
            path: "demo-1.0.dist-info/RECORD".to_owned(),
            hash: None,
            size: None,
        }]);

        assert_eq!(record, "demo-1.0.dist-info/RECORD,,\n");
    }
}
